// <auto-generated />
namespace BankOfBIT_YZ.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addNavigation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addNavigation));
        
        string IMigrationMetadata.Id
        {
            get { return "202210171626368_addNavigation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
